### ISSUE TITLE
Try on another machine, bug in xml_from_dict["cas:attributes"]

### ISSUE THREAD

**Issue by jhautefeuille** [cameronbwhite/Flask-CAS#34] opened 2015-12-01 10:46 UTC
DEBUG in routing [/usr/local/lib/python2.7/dist-packages/flask_cas/routing.py:122]:
  valid
  --------------------------------------------------------------------------------
  127.0.0.1 - - [01/Dec/2015 11:34:36] "GET /login/?ticket=ST-35015-l9COngjb5Padh3tfyJA9-  sso.inserm.fr HTTP/1.1" 500 -
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/usr/local/lib/python2.7/dist-packages/flask_cas/routing.py", line 45, in login
    if validate(flask.session[cas_token_session_key]):
    File "/usr/local/lib/python2.7/dist-packages/flask_cas/routing.py", line 125, in validate
    attributes = xml_from_dict["cas:attributes"]
    KeyError: 'cas:attributes'

Have you advice for me to resolv it ?

**Comment by cameronbwhite** [comment] 2016-01-12 05:34
Duplicate of #31

**Closed by cameronbwhite** 2016-01-12 05:34 UTC
